### PR TITLE
fix: fixed width and height for native side

### PR DESCRIPTION
**Pull request by kyawthura-gg**
Fixed width and height not working on native side

### CODE REVIEW

**Comment by nandorojo** [comment]
Is this the correct behavior? Does next/image’s height and width get styled by the props passed to it?

**Comment by kyawthura-gg** [comment]
Not sure it's correct behavior or not in next/image but passing width and height props doesn't work in native(ios/android) side. Let me know if you want reproduced repo for this issue.

**Comment by nandorojo** [comment]
I think you should just pass height and width in the `style` prop. However, if `next/image` does this for you, then I’ll accept this PR.

**Comment by kyawthura-gg** [comment]
Yes, passing height and width in the `style` prop works but also need to pass `height` and `width` props for `next/image`. To make it works in web and native, I will need to pass height and width in the `style` and `height` and `width`. I think it will be better if we can use `height` and `width` props for web and native. I can also improve this PR not to effect for web side by adding `Platform.select`.

**Comment by nandorojo** [comment]
What I'm asking is, what does `next/image` do? Does it automatically apply styles based on the `height` and `width` prop on Web, or not? The native implementation is supposed to match what `next/image` does.

**Comment by kyawthura-gg** [comment]
I'm not 100% sure. Yes, it does apply styles based on `height` and `width` prop. `next/image` also have [sizes](https://nextjs.org/docs/api-reference/next/image#sizes). For that reason, I think it's better to fix for native side.

**Comment by nandorojo** [comment]
I just released this in my own PR in v2.1.3. I’ll give you credit in release notes though, thanks for this!

**Pull request closed without merging**
