### PR TITLE
fix: update dependencies and configurations for Expo and Next.js

### PR DESCRIPTION
**Pull request by ktkennychow**
Updates various dependencies and configurations in the monorepo starter:

- Upgrade Expo and related packages to latest compatible versions
- Remove expo-router/babel plugin from Expo babel config
- Update React Native and related packages
- Adjust TypeScript and other dev dependencies
- Switch from Bun to Yarn as the package manager
- Add autoprefixer as a dev dependency
- Update scripts to use Yarn instead of Bun

### CODE REVIEW

**Comment by ktkennychow** [comment]
Since the starter uses quite a lot of dependencies, it might be a good idea to use "~" instead of "^" for some major lib like expo, react-native, etc to be more safe.

**Comment by nandorojo** [comment]
The safest thing is to use neither. It should be fixed, exact versions.

**Comment by nandorojo** [comment]
@ktkennychow any shot you could make the same changes in the blank template? Would be super appreciated 🙏🙏

**Comment by nandorojo** [comment]
Sounds good. `expo upgrade` will set the versions to `~`.

Most important thing in a react monorepo is avoiding differing versions. As long as the same version is set in two places and saved in a lock file without `^` it should be okay

**Comment by ktkennychow** [comment]
@nandorojo updated and tested /blank & /with-expo-router starters.

**Comment by nandorojo** [comment]
Thank you! 

We reverted the previous PR that broke things, which looks like this introduced some conflicts…

I think we’d just need to fix the package.json files and run yarn to fix the lock files. Let me know if you need help

**Comment by ktkennychow** [comment]
@nandorojo hmm that's exactly what I did, only "fix the package.json files and run yarn to fix the lock files", plus changing most dependencies to prefixed "~" w/ some exception that requires "^" or exact version. 
The only odd one out is an URL change in `[example-monorepos/with-expo-router/apps/next/next-env.d.ts](https://github.com/nandorojo/solito/pull/491/files#diff-307a8b5419151cba243e9a8f37d28b29736b3a241198b8748bd927d283bf5bcc)` but this one in my commit is actually the correct one.

Do you mean I fork again to test against the reverted repo?

**Comment by nandorojo** [comment]
I think you might need to pull in the latest master branch to resolve the conflicts

**Comment by nandorojo** [comment]
Once the package.json file(s) have no conflicts, running yarn will fix lock file conflicts

**Comment by ktkennychow** [comment]
@nandorojo seems like the revert got the starters working again, I will close this PR since it is not necessary.

**Pull request closed without merging**
