### PR TITLE
Add Firebase Auth guide to docs 🥳

### PR DESCRIPTION
**Pull request by omervex**
# Hi 👋
This is a highly requested guide and I'm happy to contribute this pull request.

**This guide follows the best practices and suggestions, as discussed in the Solito Github discussions by Fernando and the rest.**

[Here is the fully functioning repo of the finished product](https://github.com/omervex/solito-firebase-auth-guide).
The demo is live on Vercel (link included in the guide).

# This guide explains how to:

1. Sign in users with Firebase Authentication in the Solito web and native apps.
2. Create protected routes, that can only be accessed by signed in users.

T**his guide also covers how to setup and install `react-native-firebase` for the native Solito app with EAS build.**

# Future plans
A Solito Firebase Auth starter project, with protected routes. The guide includes all of the setup we should do when creating such a starter project. My dream is a `--with-firebase` flag.

# A Question
Waiting for your review and feedback overall, but specifically I'm not sure about one thing- displaying the user page link from the homepage when a user is still not signed in: if the user is not signed in, in the demo, I'm still displaying the link to the user page, which is a protected route. It asks the user to sign in back in the homepage. But in actual real apps- this link should not be visible to the users- they should not be able to navigate to this page, unless they type it in the URL. I'm including the user profile link just to show what happens when a user navigates to a protected route. Should the link remain visible for unauthenticated users?

### CODE REVIEW

**Review by Rychillie — APPROVED** [review]

**Review by chrisarts — APPROVED** [review]

**Comment by omervex** [comment]
@nandorojo After seeing you in Next.js conf (thanks, was awesome!), I'm thinking of making a few changes, that will reflect the project structure you showed (for example, adding a `packages/app/auth/firebase/index.ts`, etc...). If you think I should update the guide, please let me know, will be happy to do that!

**Comment by nandorojo** [comment]
I think that would be great! You can also reference the repo I made for it.

I think we use firebase's auth lib instead of expo-auth-session etc.

**Comment by omervex** [comment]
> I think that would be great! You can also reference the repo I made for it.
> 
> I think we use firebase's auth lib instead of expo-auth-session etc.

np

**Comment by nandorojo** [comment]
Hey, thanks a lot for this! I just added a Firebase guide to the docs which has a video and code sample, so I'll probably close this out. Appreciate your getting the ball rolling on this and for contributing.


https://solito.dev/guides/auth

**Pull request closed without merging**
