### PR TITLE
feat: add NestJs example repo

### PR DESCRIPTION
**Pull request by michaelangrivera**
Hi @nandorojo and other contributors! 

I'd like to contribute back and add some of the things I've learned while building my own app using this framework. This adds another example monorepo that includes a `NestJs` backend. It borrows from [this repo](https://github.com/ejazahm3d/fullstack-turborepo-starter) but with a lot stripped out. 

I've also included an important note under **Resources** in the docs for users that are trying to add other services to the monorepo and are experiencing a `jest-haste-map` collision error. I'll point out those important details in the PR itself. 

Let me know if you'd like to change anything! I'd tried to keep it as minimal as possible. 

Thank you!

### CODE REVIEW

**Comment by nandorojo** [comment]
Hey, thanks for this! I think it may be best for it to live outside of the Solito repo since I'm not familiar with Nestjs. I'm happy to link to it from the docs though. How does that sound?

**Comment by michaelangrivera** [comment]
@nandorojo Sounds great! I'll make some changes and tag you when they're ready.

**Comment by michaelangrivera** [comment]
@nandorojo how does this look?

**Comment by nandorojo** [comment]
Could you mention that the metro file is in apps/expo?

**Comment by michaelangrivera** [comment]
@nandorojo updated 🤙

**Comment by nandorojo** [comment]
It also might help if you update the readme here to explain what the additions are / remove the `npx create-solito-app` part

https://github.com/michaelangrivera/solito-nestjs-example/tree/nestjs-example-repo/example-monorepos/nestjs-example

**Comment by michaelangrivera** [comment]
@nandorojo, I'm going to close this for now. There are some gotchas I still need to work out. Will re-open when I have updates! Thank you.

**Comment by nandorojo** [comment]
cool! it could be a good fit for a blog post rather than docs, and then you could share it in a discussion & on twitter

**Comment by michaelangrivera** [comment]
@nandorojo 100% would be great. I found a lot of dependencies (maybe from turbo) slipping into the Nest app, and vice-versa, could've been from lack of turbo knowledge. 

And you should definitely give it a spin! NestJS makes my backend life pretty easy. Opinionated, but powerful.

**Pull request closed without merging**
